version: 0.1

phases:
  build:
    command:
      - echo Nothing to do yet
      - npm install
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - resume.pdf
    - styles/*
    - images/*